### ISSUE TITLE
mqtt configuration

### ISSUE THREAD

**Issue by svalavuo** [mqtt-home/groheondus-to-mqtt-gw#41]
Hi,
I disturb again. :-)
I'd like to change mqtt -server and the new one requires authentication.
Is there a configuration option for mqtt user & password?

- Samuli

**Comment by philipparndt** [comment]
Hi @svalavuo,

this projects clearly lacks some documentation 😄 
I've added an [full example configuration](https://github.com/mqtt-home/groheondus-to-mqtt-gw/blob/master/config-example.json) with username/password settings.

you can configure this in the MQTT section:
```json
{
    "mqtt": {
        "username": "mqtt_username",
        "password": "mqtt_password",
        ...
    },
    "grohe": {
        ...
    }
}
```
